package com.Inheritance;

public class Child extends Parent {

	/* this code is generated by compiler
	Child() {
		super();
		}
*/	
	public static void main(String[] args) {

		new Child();
	}

}

/*output:
parent class constructor
constructor executed without using super() keyword by user
*/